defaults:
  - model: xgboost
  - training: fit_trainer
  - strategy: group_shuffle_split
  - _self_
  - override hydra/job_logging: custom

ignore_columns: ['target', 'image']
target_column: 'target'
seed: 42
test_size: 0.2

use_prior_adjustment: true

paths: 
  results_dir: results/
  input_path: /raid/home/llmsosmed/my_folder/meta-features/20251208_175315_meta_dataset.parquet