defaults:
  - model: resnet18
  - strategy: kfold_cross_validation
  - dataset: parquet_class_data
  - dataloader: class_data
  - validation: transformer_validator
  - loss: cross_entropy
  - _self_
  - override hydra/job_logging: custom

device: cuda:7

model_folder: /raid/home/llmsosmed/my_folder/seeing-is-believing/results/dual_phase/resnet-18/phase_2/20251207-171013

save_path: /raid/home/llmsosmed/my_folder/meta-features

seed: 42

paths: 
  data_dir: /raid/home/llmsosmed/my_folder/images.parquet
  results_dir: results/
  csv_file: /raid/home/llmsosmed/my_folder/seeing-is-believing/notebooks/ISIC2018_Task3_Training_Input/cleaned_data.csv