defaults:
  - model: dpn92
  - strategy: kfold_cross_validation
  - dataset: parquet_class_data
  - dataloader: class_data
  - validation: timm_validator
  - loss: cross_entropy
  - _self_
  - override hydra/job_logging: custom

device: cuda:6

model_folder: /raid/home/llmsosmed/my_folder/seeing-is-believing/results/dpn-92/20251207-124522

save_path: /raid/home/llmsosmed/my_folder/meta-features

seed: 42

paths: 
  data_dir: /raid/home/llmsosmed/my_folder/images.parquet
  results_dir: results/
  csv_file: /raid/home/llmsosmed/my_folder/seeing-is-believing/notebooks/ISIC2018_Task3_Training_Input/cleaned_data.csv